import "./globals.css";
import "@repo/ui/styles.css";
import {Button} from "@repo/ui/button";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}> <Button appName="web" className={"flex"}>
       Click me!
       Click me now!
      </Button></body>
    </html>
  );
}
